### ISSUE TITLE
Website no longer working properly?

### ISSUE THREAD

**Issue by SereneFrost72** [platky/PkmnIssues#11]
I recently said how I was unable to get the website to work on my Android phone in Chrome because it kept saying "Please enable javascript if you have not", even though I had Java enabled. However, this error now occurs in both Chrome and Internet Explorer on a desktop computer as well. Any ideas on why this is occurring? 
![capture](https://cloud.githubusercontent.com/assets/14189818/9795136/ebcfff26-57bc-11e5-8546-7fcaa85ef518.PNG)

**Comment by platky** [comment]
That's really odd, still seems to be working for me on all the various browsers including my android phone. Can you do me a favor and open the console window in chrome on your computer? You can do this by right clicking the screen, hitting inspect element, then one of the bottom tabs will say "console". It will most likely be giving you a red error of some kind.

**Comment by SereneFrost72** [comment]
This is the error that I am receiving.

![capture](https://cloud.githubusercontent.com/assets/14189818/9799976/639223d4-57d8-11e5-8b19-fe694eb26923.PNG)

**Comment by platky** [comment]
Give it another shot and see if it works now

**Comment by SereneFrost72** [comment]
The issue was with not putting the preceding "www.". So it works now if I entirely type out www.pkmncardsonline.com/collection in the address bar. However, it still won't work if I do not type the www.

**Comment by platky** [comment]
Indeed that was the issue. The one without the www. should be getting redirected to having www. but it does not seem to be working for you which is weird. As you said just make sure the www. is there for now while I figure out why it isn't redirecting properly. Thanks for the help!

**Comment by platky** [comment]
This should be fixed. if anyone has this issue still try clearing your cache. If it still doesn't work let me know.
