### ISSUE TITLE
Set Forward/Back arrows cover up everything in between them

### ISSUE THREAD

**Issue by SereneFrost72** [platky/PkmnIssues#13]
As the title states, the arrows on the left and right of the screen when within a set's card list cover up the entire width of the page. This disallows selecting text between then and, more importantly, prohibits the use of the collection + and - buttons unless you scroll and move the arrows out of the range you are trying to adjust. Below is an image of the arrows/buttons I am talking about:

![capture](https://cloud.githubusercontent.com/assets/14189818/9817768/df0dcbd6-5872-11e5-945a-5fe43f673921.PNG)

**Comment by platky** [comment]
That will teach me to implement something without fully testing. Should be fixed now.
