### ISSUE TITLE
Signing In

### ISSUE THREAD

**Issue by platky** [platky/PkmnIssues#17]
If you are having trouble signing in let me know and I will generate a temporary password for you. There was some encoding issues with salts when I was transferring information. I am in the process of setting up a formal password reset currently.

**Comment by SereneFrost72** [comment]
I just tried and it keeps saying that my password is incorrect. Can you send me a temporary password?

**Comment by platky** [comment]
Sent. You will be able to change it back to whatever you want later tonight.

**Comment by SereneFrost72** [comment]
I received the temporary password, but whenever I go into settings and click "Attempt Reset" it does not do anything. Also, the wording on that should probably be "Attempt Update". Reset makes it seem like you will be sent another temporary password.

**Comment by platky** [comment]
Wasnt done coding it but it should work now. Let me know if you have any trouble.

**Comment by SereneFrost72** [comment]
Looks like the password change function is working now, thanks!
