### ISSUE TITLE
Easier Navigation

### ISSUE THREAD

**Issue by platky** [platky/PkmnIssues#4]
Implement in-set navigation

**Comment by aoshiz** [comment]
it is possible to have a search for cards, not only for sets?

for example: i want to register my blastoise, but the search narrows to plasma BLAST.

**Comment by platky** [comment]
Currently it gathers card data incrementally. If you click into a set you can search anything within the set but not across multiple sets. With the current way it is structured  I believe it would slow the application down too much.

**Comment by platky** [comment]
Simple in-set navigation implemented
